# Generated by Django 2.0 on 2018-04-21 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('s13worklog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logitem',
            options={'ordering': ['owner', 'start_dt'], 'verbose_name': 'Log Item', 'verbose_name_plural': 'Log Items'},
        ),
        migrations.AlterField(
            model_name='logitem',
            name='start_dt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date and Time'),
            preserve_default=False,
        ),
    ]
