# Generated by Django 2.0 on 2018-05-01 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s13worklog', '0002_auto_20180421_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
    ]
